### ISSUE TITLE
Remove SpanPropagatingExecutors

### ISSUE THREAD

**Issue by yurishkuro** [opentracing-contrib/java-spanmanager#10]
I suggest removing this class, because it extends the API surface without a lot of benefit. The same can be achieved by using the official Executors factory and then wrapping it with span manager. Using the official factory is well understood. Using this one-off factory makes people question what exactly it does.

**Comment by sjoerdtalsma** [comment]
Does it? I thought the behaviour would be almost trivially understood.
If it causes confusion in any way, I have no problem to removing it however..

**Comment by yurishkuro** [comment]
It's a delegation that can only be understood by reading docs or source of those method. Personally I would rather use standard Executors class and wrap that with span manager.
