### ISSUE TITLE
Rename repo.

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/java-spanmanager#2]
This repository came into existence as 'overflow' from [java-globaltracer](https://github.com/opentracing-contrib/java-globaltracer).

The code was then concerned with _active spans_.  
During review of the initial PR it became clear the library is more about _span management_
and revolves around the `SpanManager` interface.

It would therefore be more logical to name this repo `java-spanmanger` or something similar.

**Comment by bhs** [comment]
Inasmuch as the "point" of this repo is a static path (perhaps via globaltracer) to an active span, there are some things I like about the current name... but agreed that `java-spanmanager` would be more accurate.

**Comment by sjoerdtalsma** [comment]
Ok, then I propose the rename to `java-spanmanager` after the initial PR #1 is merged.
