### ISSUE TITLE
Change 'currentSpan()' to return null if no current span available in the context

### ISSUE THREAD

**Issue by objectiser** [opentracing-contrib/java-spanmanager#4]
Would like to understand motivation for returning a `NoopSpan` from the `SpanManager.currentSpan()` method when no span is currently associated with the context.

I see this situation as being similar to the discussion on extracting `SpanContext` which may be corrupt or missing https://github.com/opentracing/specification/issues/33#issuecomment-275556380 - where the proposal is to have an `Extract()` that distinguishes these cases, so the application would be aware when a `SpanContext` was unavailable.

Similarly, I believe the `SpanManager` should only return a `Span` if one exists in the current application context.

Otherwise this leads to problems if attempting to add this `NoopSpan` in a `ChildOf` reference (e.g. when using the `MockTracer`) - which raises the question, should tracers be resilient to spans/contexts from other tracer implementations, but that is a different issue.

**Comment by sjoerdtalsma** [comment]
The main reason for this is that [opentracing-java](https://github.com/opentracing/opentracing-java) also defaults to NoopSpan for most operations.
I agree the discussion in https://github.com/opentracing/specification/issues/33 should provide a guideline on where to go with this.

Ideally, taking [PR 3](#3) into account, I'd like to be able to start a child without an _if_ statement.
An in-between could be that there is _always_ a current `ManagedSpan`, which may contain Span `null`.
```java
..
try (Span span = tracer.buildSpan("name").asChildOf(spanManager.current().getSpan()).start()) {
    ..
}
```
This would require an API change to explicitly ignore `null` arguments to `SpanBuilder.asChildOf()`.

Alternatively, we could reverse this and provide equivalent behaviour from the `ManagedSpan` class as follows (much less elegant in my opinion):
```java
..
try (Span span = spanManager.current().startChild(tracer.buildSpan("name"))) {
    ..
}
```
This requires a new method on `ManagedSpan` which could be conceived as:
```java
public Span startChild(SpanBuilder builder) {
    if (builder == null) throw new NullPointerException("Builder is <null>!");
    else if (span == null || span instanceof NoopSpan) return builder.start();
    else return builder.asChildOf(span.context()).start();
}
```

Or even a method `SpanManager.startNewManagedChildSpan(SpanBuilder builder)` that returns a new ManagedSpan (child if there's a managed span or new 'regular' span if there's no managed span)...

@bensigelman I'm also interested in your opinion in the various possible directions this can go.

**Comment by objectiser** [comment]
> This would require an API change to explicitly ignore null arguments to SpanBuilder.asChildOf().

Was thinking about raising this anyway - so +1 from me. This would also enable `tracer.buildSpan("name").asChildOf(tracer.extract(...))` as well, where there is no `SpanContext` available.

**Comment by bhs** [comment]
I have been thinking a lot about this topic in general lately, admittedly mostly in the context of https://github.com/opentracing/specification/issues/23 (IMO by far the most important open issue in opentracing generally).

I couldn't agree more about allowing `null` (or some `null` equivalent if there are people who want to convince me that `null` should never be used in Java) as a parameter to `childOf()`... the current interface doesn't specify semantics for `null` references either way, of course.

That said, I would find this all easier to reason about if the `currentSpan` was actually `currentSpanContext`. This would come with some limitations, of course, but it would also generalize things and deal with lifetime issues with `Span`: `Span` behavior is undefined after `finish()` is called, but `SpanContext` is evergreen.

**Comment by sjoerdtalsma** [comment]
@bensigelman Valid point about the `SpanContext` vs. `Span` matter.
It started actually as the context, but I think there was a remark re. logging that made it 'richer' if the actual span got remembered. The discussion was so long and I had to change so many things then that I don't recall it completely anymore.

I can definitely experiment changing `ManagedSpan` to `ManagedSpanContext`, but I think that should be a separate pull-request.

@bensigelman Regarding the 'null'-ish issue, would you consider a 'fresh' SpanContext to be `null` or `NoopSpanContext` ?

**Comment by bhs** [comment]
@sjoerdtalsma 

> Regarding the 'null'-ish issue, would you consider a 'fresh' SpanContext to be null or NoopSpanContext ?

Would *I* prefer `null` for that? Absolutely. But I basically don't use Java in my day-to-day job, and when I talk to 2017-style Java devs I am always surprised by what I hear. :)

That said, if we wanted a "real" type / instance to represent a missing SpanContext, I would call it like it is: `MissingSpanContext` or something like that. (It's not a "noop": it's simply not there)

**Comment by sjoerdtalsma** [comment]
> That said, if we wanted a "real" type / instance to represent a missing SpanContext, I would call it like it is: MissingSpanContext or something like that. (It's not a "noop": it's simply not there)

Interesting! I could definitely create something like that (might `EmptySpanContext` work?).
However we would soon arrive at a _very_ similar question to the OP's:
> .. which raises the question, should tracers be resilient to spans/contexts from other tracer implementations, but that is a different issue.

Spans, probably/definitively not I guess, but could we demand such a thing for `SpanContext`?
If not, would we create another exception for this `MissingSpanContext` or `EmptySpanContext`?
It somehow still feels wrong to me unless this concept is introduced into the API itself.

**Comment by objectiser** [comment]
@sjoerdtalsma @bensigelman I can see the benefit of using `SpanContext` if it was just lifetime concerns, but having the ability to define logs and tags on an existing span, created in another layer, may also be useful.

We could insist that the code wishing to record this information creates its own child span to hold these tags/logs - but just wondering if there would be cases where the application is wanting to enrich the information associated with an existing `Span`?

The reason for creating https://github.com/opentracing-contrib/java-spanmanager/pull/3 was because the span was started in one callback and finished in another - however if the 'end' callback also needs to register further tags/logs, having access to the `SpanContext` wouldn't be sufficient.

**Comment by sjoerdtalsma** [comment]
Updated code after merging PR #3 to:

- `SpanManager.current()` never to return `null`, but: `SpanManager.current().getSpan()` to return `null` if no `Span` is actually managed.
- `SpanManager.currentSpan()` will still return `NoopSpan` in this case, for backward compatibility reasons (this method is deprecated anyway and should be removed after the coming release).

I think this approach takes care of this issue as well.
This leaves the issue of 'how' to easily start a new child Span of the current() managed span _if managed_ or a new root span otherwise (preferably without IF statements).
Let's leave that up to the API spec to tackle 😉
