### ISSUE TITLE
Naming: activate/deactivate over manage/release?

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/java-spanmanager#7]
In the Distributed Tracing Workshop in Berlin there seemed to be some consensus forming on the verbs
_activate_ / _deactivate_ for in-process Span propagation.

@bhs would you agree that _activate_ / _deactivate_ speaks more of the intent than _manage_/_release_?

**Comment by bhs** [comment]
@sjoerdtalsma absolutely, yes.

That said, I have continued to work on a spike of yet another approach to this overall problem (where I'm permitting myself to change the core APIs, of course), so I'm trying not to worry too much about the naming until we have agreed on the basic moving parts.

**Comment by sjoerdtalsma** [comment]
Sounds smart and you shouldn't worry 😉 ..
However in my experience continuing to use different names for the same things should be avoided whenever possible (it can be here, by deprecation).

**Comment by sjoerdtalsma** [comment]
Created a PR #8 tackling this rename.

**Comment by sjoerdtalsma** [comment]
PR #8 was merged and released as `0.0.3`
